/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMembersByPublicId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{publicId}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMembersByPublicIdInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{publicId}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMembersByPublicIdDetail"];
        put: operations["putMembersByPublicIdDetail"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{publicId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMembersByPublicIdStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/member-status-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMemberStatusLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/member-status-logs/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMemberStatusLogsByPublicId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        type: "Success";
                        value: {
                            /** @constant */
                            message: "Meibo System V5 Backend API";
                        };
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "AUTH_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "AUTH_ERROR";
                        } | {
                            /** @description 認証・認可時のエラー */
                            detail: {
                                /**
                                 * @description `Authorization` ヘッダーの欠落
                                 * @constant
                                 */
                                type: "MISSING_AUTHORIZATION_HEADER";
                            };
                            /** @constant */
                            type: "AUTH_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            detail: {
                                /**
                                 * @description 必要な権限情報が存在しない
                                 * @constant
                                 */
                                type: "MISSING_PERMISSION_INFO";
                            };
                            /** @constant */
                            type: "PERMISSION_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
        };
    };
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功時 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        type: "Success";
                        value: {
                            /** @constant */
                            message: "OK";
                        };
                    };
                };
            };
        };
    };
    getMembers: {
        parameters: {
            query?: {
                /** @description 複数の “部員 ID” の最大取得数 */
                limit?: string;
                /** @description 取得する複数の “部員 ID” の順序のキー */
                orderKey?: "createdAt" | "updatedAt";
                /** @description 昇順 or 降順 */
                orderType?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        type: "Success";
                        value: {
                            count: number;
                            val: {
                                /**
                                 * @description ISO 8601 形式の日付文字列
                                 * @example 2024-05-19T06:55:41.603Z
                                 */
                                createdAt: string;
                                /**
                                 * @description 公開用 ID
                                 * @example muzrux3ve6jbadecs9rbimmh
                                 */
                                publicId: string;
                                /** @example U0524H34CDS */
                                slackId: string;
                                /** @description Auth0 の subject */
                                subject: string;
                                /**
                                 * @description ISO 8601 形式の日付文字列
                                 * @example 2024-05-19T06:55:41.603Z
                                 */
                                updatedAt: string;
                            }[];
                        };
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "AUTH_ERROR";
                        } | {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "REQUEST_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "AUTH_ERROR";
                        } | {
                            /** @description 認証・認可時のエラー */
                            detail: {
                                /**
                                 * @description `Authorization` ヘッダーの欠落
                                 * @constant
                                 */
                                type: "MISSING_AUTHORIZATION_HEADER";
                            };
                            /** @constant */
                            type: "AUTH_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
        };
    };
    getMembersByPublicId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 公開用 ID */
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        type: "Success";
                        /** @description 部員 ID */
                        value: {
                            /**
                             * @description ISO 8601 形式の日付文字列
                             * @example 2024-05-19T06:55:41.603Z
                             */
                            createdAt: string;
                            /**
                             * @description 公開用 ID
                             * @example muzrux3ve6jbadecs9rbimmh
                             */
                            publicId: string;
                            /** @example U0524H34CDS */
                            slackId: string;
                            /** @description Auth0 の subject */
                            subject: string;
                            /**
                             * @description ISO 8601 形式の日付文字列
                             * @example 2024-05-19T06:55:41.603Z
                             */
                            updatedAt: string;
                        };
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "AUTH_ERROR";
                        } | {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "REQUEST_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "AUTH_ERROR";
                        } | {
                            /** @description 認証・認可時のエラー */
                            detail: {
                                /**
                                 * @description `Authorization` ヘッダーの欠落
                                 * @constant
                                 */
                                type: "MISSING_AUTHORIZATION_HEADER";
                            };
                            /** @constant */
                            type: "AUTH_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "DATABASE_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
        };
    };
    getMembersByPublicIdInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 公開用 ID */
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        type: "Success";
                        value: {
                            _referenced: {
                                /** @description 部員 ID */
                                member: {
                                    /**
                                     * @description ISO 8601 形式の日付文字列
                                     * @example 2024-05-19T06:55:41.603Z
                                     */
                                    createdAt: string;
                                    /**
                                     * @description 公開用 ID
                                     * @example muzrux3ve6jbadecs9rbimmh
                                     */
                                    publicId: string;
                                    /** @example U0524H34CDS */
                                    slackId: string;
                                    /** @description Auth0 の subject */
                                    subject: string;
                                    /**
                                     * @description ISO 8601 形式の日付文字列
                                     * @example 2024-05-19T06:55:41.603Z
                                     */
                                    updatedAt: string;
                                };
                            };
                            /** @description 部員の基本情報 */
                            base: {
                                /**
                                 * @description ISO 8601 形式の日付文字列
                                 * @example 2024-05-19T06:55:41.603Z
                                 */
                                createdAt: string;
                                /** @description 名前（名） */
                                firstName: string;
                                /** @description フリガナ（名） */
                                firstNameKana: string;
                                /** @description 名前（姓） */
                                lastName: string;
                                /** @description フリガナ（姓） */
                                lastNameKana: string;
                                /**
                                 * @description ISO 8601 形式の日付文字列
                                 * @example 2024-05-19T06:55:41.603Z
                                 */
                                updatedAt: string;
                            };
                            sensitive: {
                                /**
                                 * @description ISO 8601 形式の日付文字列
                                 * @example 2024-05-19T06:55:41.603Z
                                 */
                                birthday: string;
                                /**
                                 * @description ISO 8601 形式の日付文字列
                                 * @example 2024-05-19T06:55:41.603Z
                                 */
                                createdAt: string;
                                /** @description 現住所 */
                                currentAddress: string;
                                /** @description 現住所の郵便番号 */
                                currentZipCode: string;
                                /** @description 実家の住所 */
                                parentsAddress: string;
                                /** @description 実家の郵便番号 */
                                parentsZipCode: string;
                                /** @description 電話番号 */
                                phoneNumber: string;
                                /**
                                 * @description 性別 (ISO-5218)
                                 * @enum {unknown}
                                 */
                                sex: "FEMALE" | "MALE" | "NOT_APPLICABLE" | "NOT_KNOWN";
                                /**
                                 * @description ISO 8601 形式の日付文字列
                                 * @example 2024-05-19T06:55:41.603Z
                                 */
                                updatedAt: string;
                            } | null;
                        };
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "AUTH_ERROR";
                        } | {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "REQUEST_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "AUTH_ERROR";
                        } | {
                            /** @description 認証・認可時のエラー */
                            detail: {
                                /**
                                 * @description `Authorization` ヘッダーの欠落
                                 * @constant
                                 */
                                type: "MISSING_AUTHORIZATION_HEADER";
                            };
                            /** @constant */
                            type: "AUTH_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "MEMBER_INFO_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "DATABASE_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
            /** @description Precondition Failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "MEMBER_INFO_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
        };
    };
    getMembersByPublicIdDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 公開用 ID */
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        type: "Success";
                        value: {
                            _referenced: {
                                /** @description 部員 ID */
                                member: {
                                    /**
                                     * @description ISO 8601 形式の日付文字列
                                     * @example 2024-05-19T06:55:41.603Z
                                     */
                                    createdAt: string;
                                    /**
                                     * @description 公開用 ID
                                     * @example muzrux3ve6jbadecs9rbimmh
                                     */
                                    publicId: string;
                                    /** @example U0524H34CDS */
                                    slackId: string;
                                    /** @description Auth0 の subject */
                                    subject: string;
                                    /**
                                     * @description ISO 8601 形式の日付文字列
                                     * @example 2024-05-19T06:55:41.603Z
                                     */
                                    updatedAt: string;
                                };
                            };
                            active: {
                                /** @description 部員の情報 (正規部員・外部生) */
                                detail: {
                                    /**
                                     * @description ISO 8601 形式の日付文字列
                                     * @example 2024-05-19T06:55:41.603Z
                                     */
                                    createdAt: string;
                                    /** @description 所属 */
                                    organization: string;
                                    /** @description 学科 */
                                    schoolMajor: string;
                                    /** @description 学校名 */
                                    schoolName: string;
                                    /**
                                     * @description ISO 8601 形式の日付文字列
                                     * @example 2024-05-19T06:55:41.603Z
                                     */
                                    updatedAt: string;
                                };
                                /** @constant */
                                type: "EXTERNAL";
                            };
                            /** @description 部員の情報 (正規部員) */
                            detail: {
                                /**
                                 * @description ISO 8601 形式の日付文字列
                                 * @example 2024-05-19T06:55:41.603Z
                                 */
                                createdAt: string;
                                /** @description 学年 */
                                grade: "B1" | "B2" | "B3" | "M1" | "M2";
                                /**
                                 * @description ISO 8601 形式の日付文字列
                                 * @example 2024-05-19T06:55:41.603Z
                                 */
                                updatedAt: string;
                            };
                            /** @constant */
                            type: "ACTIVE";
                        } | {
                            _referenced: {
                                /** @description 部員 ID */
                                member: {
                                    /**
                                     * @description ISO 8601 形式の日付文字列
                                     * @example 2024-05-19T06:55:41.603Z
                                     */
                                    createdAt: string;
                                    /**
                                     * @description 公開用 ID
                                     * @example muzrux3ve6jbadecs9rbimmh
                                     */
                                    publicId: string;
                                    /** @example U0524H34CDS */
                                    slackId: string;
                                    /** @description Auth0 の subject */
                                    subject: string;
                                    /**
                                     * @description ISO 8601 形式の日付文字列
                                     * @example 2024-05-19T06:55:41.603Z
                                     */
                                    updatedAt: string;
                                };
                            };
                            active: {
                                /** @description 部員の情報 (正規部員・内部生) */
                                detail: {
                                    /**
                                     * @description ISO 8601 形式の日付文字列
                                     * @example 2024-05-19T06:55:41.603Z
                                     */
                                    createdAt: string;
                                    /** @description 役職 */
                                    role: string | null;
                                    /** @description 学籍番号 */
                                    studentId: string;
                                    /**
                                     * @description ISO 8601 形式の日付文字列
                                     * @example 2024-05-19T06:55:41.603Z
                                     */
                                    updatedAt: string;
                                };
                                /** @constant */
                                type: "INTERNAL";
                            };
                            /** @description 部員の情報 (正規部員) */
                            detail: {
                                /**
                                 * @description ISO 8601 形式の日付文字列
                                 * @example 2024-05-19T06:55:41.603Z
                                 */
                                createdAt: string;
                                /** @description 学年 */
                                grade: "B1" | "B2" | "B3" | "M1" | "M2";
                                /**
                                 * @description ISO 8601 形式の日付文字列
                                 * @example 2024-05-19T06:55:41.603Z
                                 */
                                updatedAt: string;
                            };
                            /** @constant */
                            type: "ACTIVE";
                        } | {
                            _referenced: {
                                /** @description 部員 ID */
                                member: {
                                    /**
                                     * @description ISO 8601 形式の日付文字列
                                     * @example 2024-05-19T06:55:41.603Z
                                     */
                                    createdAt: string;
                                    /**
                                     * @description 公開用 ID
                                     * @example muzrux3ve6jbadecs9rbimmh
                                     */
                                    publicId: string;
                                    /** @example U0524H34CDS */
                                    slackId: string;
                                    /** @description Auth0 の subject */
                                    subject: string;
                                    /**
                                     * @description ISO 8601 形式の日付文字列
                                     * @example 2024-05-19T06:55:41.603Z
                                     */
                                    updatedAt: string;
                                };
                            };
                            /** @description 部員の情報 (卒業部員) */
                            detail: {
                                /**
                                 * @description ISO 8601 形式の日付文字列
                                 * @example 2024-05-19T06:55:41.603Z
                                 */
                                createdAt: string;
                                /** @description 卒業年 */
                                graduatedYear: number;
                                /** @description 旧役職 */
                                oldRole: string | null;
                                /**
                                 * @description ISO 8601 形式の日付文字列
                                 * @example 2024-05-19T06:55:41.603Z
                                 */
                                updatedAt: string;
                            };
                            /** @constant */
                            type: "ALUMNI";
                        };
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "AUTH_ERROR";
                        } | {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "REQUEST_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "AUTH_ERROR";
                        } | {
                            /** @description 認証・認可時のエラー */
                            detail: {
                                /**
                                 * @description `Authorization` ヘッダーの欠落
                                 * @constant
                                 */
                                type: "MISSING_AUTHORIZATION_HEADER";
                            };
                            /** @constant */
                            type: "AUTH_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "MEMBER_DETAIL_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "DATABASE_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
            /** @description Precondition Failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "MEMBER_DETAIL_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
        };
    };
    putMembersByPublicIdDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 公開用 ID */
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    active: {
                        /** @description 部員の情報 (正規部員・外部生) */
                        detail: {
                            /** @description an integer representing a safe Unix timestamp */
                            createdAt: number;
                            /** @description 所属 */
                            organization: string;
                            /** @description 学科 */
                            schoolMajor: string;
                            /** @description 学校名 */
                            schoolName: string;
                            /** @description an integer representing a safe Unix timestamp */
                            updatedAt: number;
                        };
                        /** @constant */
                        type: "EXTERNAL";
                    };
                    /** @description 部員の情報 (正規部員) */
                    detail: {
                        /** @description an integer representing a safe Unix timestamp */
                        createdAt: number;
                        /** @description 学年 */
                        grade: "B1" | "B2" | "B3" | "M1" | "M2";
                        /** @description an integer representing a safe Unix timestamp */
                        updatedAt: number;
                    };
                    /** @constant */
                    type: "ACTIVE";
                } | {
                    active: {
                        /** @description 部員の情報 (正規部員・内部生) */
                        detail: {
                            /** @description an integer representing a safe Unix timestamp */
                            createdAt: number;
                            /** @description 役職 */
                            role: string | null;
                            /** @description 学籍番号 */
                            studentId: string;
                            /** @description an integer representing a safe Unix timestamp */
                            updatedAt: number;
                        };
                        /** @constant */
                        type: "INTERNAL";
                    };
                    /** @description 部員の情報 (正規部員) */
                    detail: {
                        /** @description an integer representing a safe Unix timestamp */
                        createdAt: number;
                        /** @description 学年 */
                        grade: "B1" | "B2" | "B3" | "M1" | "M2";
                        /** @description an integer representing a safe Unix timestamp */
                        updatedAt: number;
                    };
                    /** @constant */
                    type: "ACTIVE";
                } | {
                    /** @description 部員の情報 (卒業部員) */
                    detail: {
                        /** @description an integer representing a safe Unix timestamp */
                        createdAt: number;
                        /** @description 卒業年 */
                        graduatedYear: number;
                        /** @description 旧役職 */
                        oldRole: string | null;
                        /** @description an integer representing a safe Unix timestamp */
                        updatedAt: number;
                    };
                    /** @constant */
                    type: "ALUMNI";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        type: "Success";
                        value: {
                            active: {
                                /** @description 部員の情報 (正規部員・外部生) */
                                detail: {
                                    /** @description an integer representing a safe Unix timestamp */
                                    createdAt: number;
                                    /** @description 所属 */
                                    organization: string;
                                    /** @description 学科 */
                                    schoolMajor: string;
                                    /** @description 学校名 */
                                    schoolName: string;
                                    /** @description an integer representing a safe Unix timestamp */
                                    updatedAt: number;
                                };
                                /** @constant */
                                type: "EXTERNAL";
                            };
                            /** @description 部員の情報 (正規部員) */
                            detail: {
                                /** @description an integer representing a safe Unix timestamp */
                                createdAt: number;
                                /** @description 学年 */
                                grade: "B1" | "B2" | "B3" | "M1" | "M2";
                                /** @description an integer representing a safe Unix timestamp */
                                updatedAt: number;
                            };
                            /** @constant */
                            type: "ACTIVE";
                        } | {
                            active: {
                                /** @description 部員の情報 (正規部員・内部生) */
                                detail: {
                                    /** @description an integer representing a safe Unix timestamp */
                                    createdAt: number;
                                    /** @description 役職 */
                                    role: string | null;
                                    /** @description 学籍番号 */
                                    studentId: string;
                                    /** @description an integer representing a safe Unix timestamp */
                                    updatedAt: number;
                                };
                                /** @constant */
                                type: "INTERNAL";
                            };
                            /** @description 部員の情報 (正規部員) */
                            detail: {
                                /** @description an integer representing a safe Unix timestamp */
                                createdAt: number;
                                /** @description 学年 */
                                grade: "B1" | "B2" | "B3" | "M1" | "M2";
                                /** @description an integer representing a safe Unix timestamp */
                                updatedAt: number;
                            };
                            /** @constant */
                            type: "ACTIVE";
                        } | {
                            /** @description 部員の情報 (卒業部員) */
                            detail: {
                                /** @description an integer representing a safe Unix timestamp */
                                createdAt: number;
                                /** @description 卒業年 */
                                graduatedYear: number;
                                /** @description 旧役職 */
                                oldRole: string | null;
                                /** @description an integer representing a safe Unix timestamp */
                                updatedAt: number;
                            };
                            /** @constant */
                            type: "ALUMNI";
                        };
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "AUTH_ERROR";
                        } | {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "REQUEST_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "AUTH_ERROR";
                        } | {
                            /** @description 認証・認可時のエラー */
                            detail: {
                                /**
                                 * @description `Authorization` ヘッダーの欠落
                                 * @constant
                                 */
                                type: "MISSING_AUTHORIZATION_HEADER";
                            };
                            /** @constant */
                            type: "AUTH_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "MEMBER_DETAIL_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "DATABASE_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
            /** @description Precondition Failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "MEMBER_DETAIL_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
        };
    };
    getMembersByPublicIdStatus: {
        parameters: {
            query?: {
                /** @description 複数の “部員の状態ログ” の最大取得数 */
                limit?: string;
                /** @description 取得する複数の “部員の状態ログ” の順序のキー */
                orderKey?: "createdAt" | "rejectedAt" | "updatedAt";
                /** @description 昇順 or 降順 */
                orderType?: "asc" | "desc";
            };
            header?: never;
            path: {
                /** @description 公開用 ID */
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        type: "Success";
                        value: {
                            count: number;
                            /** @description 部員の現在の状態 */
                            currentStatus: "ACTIVE" | "ACTIVE_PENDING" | "BEFORE_REGISTER" | "LEAVE" | "RENEW" | "RENEW_PROCESS_PENDING";
                            /** @description 部員の現在の状態 (詳細) */
                            currentStatusDetail: "REGISTER_REJECTED_PENDING" | null;
                            val: {
                                _computed: {
                                    /** @description 拒否されたか */
                                    hasRejected: boolean;
                                };
                                _referenced: {
                                    /** @description 部員 ID */
                                    member: {
                                        /**
                                         * @description ISO 8601 形式の日付文字列
                                         * @example 2024-05-19T06:55:41.603Z
                                         */
                                        createdAt: string;
                                        /**
                                         * @description 公開用 ID
                                         * @example muzrux3ve6jbadecs9rbimmh
                                         */
                                        publicId: string;
                                        /** @example U0524H34CDS */
                                        slackId: string;
                                        /** @description Auth0 の subject */
                                        subject: string;
                                        /**
                                         * @description ISO 8601 形式の日付文字列
                                         * @example 2024-05-19T06:55:41.603Z
                                         */
                                        updatedAt: string;
                                    };
                                    /** @description 拒否した部員 */
                                    rejectedBy: {
                                        /**
                                         * @description ISO 8601 形式の日付文字列
                                         * @example 2024-05-19T06:55:41.603Z
                                         */
                                        createdAt: string;
                                        /**
                                         * @description 公開用 ID
                                         * @example muzrux3ve6jbadecs9rbimmh
                                         */
                                        publicId: string;
                                        /** @example U0524H34CDS */
                                        slackId: string;
                                        /** @description Auth0 の subject */
                                        subject: string;
                                        /**
                                         * @description ISO 8601 形式の日付文字列
                                         * @example 2024-05-19T06:55:41.603Z
                                         */
                                        updatedAt: string;
                                    } | null;
                                    /** @description 部員 ID */
                                    updatedBy: {
                                        /**
                                         * @description ISO 8601 形式の日付文字列
                                         * @example 2024-05-19T06:55:41.603Z
                                         */
                                        createdAt: string;
                                        /**
                                         * @description 公開用 ID
                                         * @example muzrux3ve6jbadecs9rbimmh
                                         */
                                        publicId: string;
                                        /** @example U0524H34CDS */
                                        slackId: string;
                                        /** @description Auth0 の subject */
                                        subject: string;
                                        /**
                                         * @description ISO 8601 形式の日付文字列
                                         * @example 2024-05-19T06:55:41.603Z
                                         */
                                        updatedAt: string;
                                    };
                                };
                                /**
                                 * @description ISO 8601 形式の日付文字列
                                 * @example 2024-05-19T06:55:41.603Z
                                 */
                                createdAt: string;
                                /**
                                 * @description 公開用 ID
                                 * @example muzrux3ve6jbadecs9rbimmh
                                 */
                                publicId: string;
                                rejectedAt: string | null;
                                /** @description 部員の状態 */
                                status: "ACTIVE" | "ACTIVE_PENDING" | "LEAVE" | "RENEW";
                                /**
                                 * @description ISO 8601 形式の日付文字列
                                 * @example 2024-05-19T06:55:41.603Z
                                 */
                                updatedAt: string;
                            }[];
                        };
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "AUTH_ERROR";
                        } | {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "REQUEST_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "AUTH_ERROR";
                        } | {
                            /** @description 認証・認可時のエラー */
                            detail: {
                                /**
                                 * @description `Authorization` ヘッダーの欠落
                                 * @constant
                                 */
                                type: "MISSING_AUTHORIZATION_HEADER";
                            };
                            /** @constant */
                            type: "AUTH_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "DATABASE_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
        };
    };
    getMemberStatusLogs: {
        parameters: {
            query?: {
                /** @description 複数の “部員の状態ログ” の最大取得数 */
                limit?: string;
                /** @description 取得する複数の “部員の状態ログ” の順序のキー */
                orderKey?: "createdAt" | "rejectedAt" | "updatedAt";
                /** @description 昇順 or 降順 */
                orderType?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        type: "Success";
                        value: {
                            count: number;
                            /** @description 部員の現在の状態 */
                            currentStatus: "ACTIVE" | "ACTIVE_PENDING" | "BEFORE_REGISTER" | "LEAVE" | "RENEW" | "RENEW_PROCESS_PENDING";
                            /** @description 部員の現在の状態 (詳細) */
                            currentStatusDetail: "REGISTER_REJECTED_PENDING" | null;
                            val: {
                                _computed: {
                                    /** @description 拒否されたか */
                                    hasRejected: boolean;
                                };
                                _referenced: {
                                    /** @description 部員 ID */
                                    member: {
                                        /**
                                         * @description ISO 8601 形式の日付文字列
                                         * @example 2024-05-19T06:55:41.603Z
                                         */
                                        createdAt: string;
                                        /**
                                         * @description 公開用 ID
                                         * @example muzrux3ve6jbadecs9rbimmh
                                         */
                                        publicId: string;
                                        /** @example U0524H34CDS */
                                        slackId: string;
                                        /** @description Auth0 の subject */
                                        subject: string;
                                        /**
                                         * @description ISO 8601 形式の日付文字列
                                         * @example 2024-05-19T06:55:41.603Z
                                         */
                                        updatedAt: string;
                                    };
                                    /** @description 拒否した部員 */
                                    rejectedBy: {
                                        /**
                                         * @description ISO 8601 形式の日付文字列
                                         * @example 2024-05-19T06:55:41.603Z
                                         */
                                        createdAt: string;
                                        /**
                                         * @description 公開用 ID
                                         * @example muzrux3ve6jbadecs9rbimmh
                                         */
                                        publicId: string;
                                        /** @example U0524H34CDS */
                                        slackId: string;
                                        /** @description Auth0 の subject */
                                        subject: string;
                                        /**
                                         * @description ISO 8601 形式の日付文字列
                                         * @example 2024-05-19T06:55:41.603Z
                                         */
                                        updatedAt: string;
                                    } | null;
                                    /** @description 部員 ID */
                                    updatedBy: {
                                        /**
                                         * @description ISO 8601 形式の日付文字列
                                         * @example 2024-05-19T06:55:41.603Z
                                         */
                                        createdAt: string;
                                        /**
                                         * @description 公開用 ID
                                         * @example muzrux3ve6jbadecs9rbimmh
                                         */
                                        publicId: string;
                                        /** @example U0524H34CDS */
                                        slackId: string;
                                        /** @description Auth0 の subject */
                                        subject: string;
                                        /**
                                         * @description ISO 8601 形式の日付文字列
                                         * @example 2024-05-19T06:55:41.603Z
                                         */
                                        updatedAt: string;
                                    };
                                };
                                /**
                                 * @description ISO 8601 形式の日付文字列
                                 * @example 2024-05-19T06:55:41.603Z
                                 */
                                createdAt: string;
                                /**
                                 * @description 公開用 ID
                                 * @example muzrux3ve6jbadecs9rbimmh
                                 */
                                publicId: string;
                                rejectedAt: string | null;
                                /** @description 部員の状態 */
                                status: "ACTIVE" | "ACTIVE_PENDING" | "LEAVE" | "RENEW";
                                /**
                                 * @description ISO 8601 形式の日付文字列
                                 * @example 2024-05-19T06:55:41.603Z
                                 */
                                updatedAt: string;
                            }[];
                        };
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "REQUEST_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
        };
    };
    getMemberStatusLogsByPublicId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 公開用 ID */
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        type: "Success";
                        value: {
                            _computed: {
                                /** @description 拒否されたか */
                                hasRejected: boolean;
                            };
                            _referenced: {
                                /** @description 部員 ID */
                                member: {
                                    /**
                                     * @description ISO 8601 形式の日付文字列
                                     * @example 2024-05-19T06:55:41.603Z
                                     */
                                    createdAt: string;
                                    /**
                                     * @description 公開用 ID
                                     * @example muzrux3ve6jbadecs9rbimmh
                                     */
                                    publicId: string;
                                    /** @example U0524H34CDS */
                                    slackId: string;
                                    /** @description Auth0 の subject */
                                    subject: string;
                                    /**
                                     * @description ISO 8601 形式の日付文字列
                                     * @example 2024-05-19T06:55:41.603Z
                                     */
                                    updatedAt: string;
                                };
                                /** @description 拒否した部員 */
                                rejectedBy: {
                                    /**
                                     * @description ISO 8601 形式の日付文字列
                                     * @example 2024-05-19T06:55:41.603Z
                                     */
                                    createdAt: string;
                                    /**
                                     * @description 公開用 ID
                                     * @example muzrux3ve6jbadecs9rbimmh
                                     */
                                    publicId: string;
                                    /** @example U0524H34CDS */
                                    slackId: string;
                                    /** @description Auth0 の subject */
                                    subject: string;
                                    /**
                                     * @description ISO 8601 形式の日付文字列
                                     * @example 2024-05-19T06:55:41.603Z
                                     */
                                    updatedAt: string;
                                } | null;
                                /** @description 部員 ID */
                                updatedBy: {
                                    /**
                                     * @description ISO 8601 形式の日付文字列
                                     * @example 2024-05-19T06:55:41.603Z
                                     */
                                    createdAt: string;
                                    /**
                                     * @description 公開用 ID
                                     * @example muzrux3ve6jbadecs9rbimmh
                                     */
                                    publicId: string;
                                    /** @example U0524H34CDS */
                                    slackId: string;
                                    /** @description Auth0 の subject */
                                    subject: string;
                                    /**
                                     * @description ISO 8601 形式の日付文字列
                                     * @example 2024-05-19T06:55:41.603Z
                                     */
                                    updatedAt: string;
                                };
                            };
                            /**
                             * @description ISO 8601 形式の日付文字列
                             * @example 2024-05-19T06:55:41.603Z
                             */
                            createdAt: string;
                            /**
                             * @description 公開用 ID
                             * @example muzrux3ve6jbadecs9rbimmh
                             */
                            publicId: string;
                            rejectedAt: string | null;
                            /** @description 部員の状態 */
                            status: "ACTIVE" | "ACTIVE_PENDING" | "LEAVE" | "RENEW";
                            /**
                             * @description ISO 8601 形式の日付文字列
                             * @example 2024-05-19T06:55:41.603Z
                             */
                            updatedAt: string;
                        };
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "REQUEST_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @enum {unknown} */
                            detail: never;
                            /** @constant */
                            type: "DATABASE_ERROR";
                        };
                        /** @constant */
                        type: "Failure";
                    };
                };
            };
        };
    };
}
